import Head from "next/head";
import React, { useEffect } from "react";
import styles from "../styles/Home.module.css";
import nextPackage from "next/package.json";
import { getWordlist } from "utils/words";

export default function Home({}) {
  const [randWord, setRandWord] = React.useState("");

  useEffect(() => {
    const listofWords = getWordlist();
    setRandWord(listofWords[Math.floor(Math.random() * listofWords.length)]);
  }
  , []);


  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a> v
          {nextPackage.version}
        </h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>

        </p>
        <br />
        <p className={styles.description}>
          Here is a random word from the word list:{" "}
          <code className={styles.code}>{randWord}</code>
        </p>


      </main>
    </div>
  );
}
