import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { getWordlist } from "utils/words";

export const getServerSideProps = async () => {
  const listofWords = getWordlist();
  const randWord = listofWords[Math.floor(Math.random() * listofWords.length)];

  return {
    props: {
      randWord,
    },
  };
}

export default function Home({randWord}) {
    

  return (
    <div className={styles.container}>
      <Head>
        <title>Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Town<a href="https://nextjs.org">le</a>
        </h1>


        <br />
        <p className={styles.description}>
          Here is a random word from the word list:{" "}
          <code className={styles.code}>{randWord}</code>
        </p>


      </main>
    </div>
  );
}
